$axure.loadCurrentPage({
  "url":"new_user_login.html",
  "generationDate":new Date(1442793700497.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17ea30054e83426f9e44cd3ef80fe819",
    "type":"Axure:Page",
    "name":"New User/Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7a66c3bd442f48cb9ed746553d032681",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFF0099FF},
{
                  "color":0xFF0099FF}]},
            "size":{
              "width":1440,
              "height":1120},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b00a2eb67a6043ada29cf9939c962ff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFF0099FF},
{
                      "color":0xFF0099FF}]},
                "size":{
                  "width":1440,
                  "height":1120},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/template/u515.png"}},
{
          "id":"6a6b3328667a425aa882e547aeae8e98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":3},
            "size":{
              "width":1020,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed31baaed9d54c32931da332ae5daa09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":3},
                "size":{
                  "width":1020,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u373.png"}},
{
          "id":"d530fe1c681f41dd92e6142ca62eda22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "location":{
              "x":586,
              "y":420},
            "size":{
              "width":349,
              "height":205},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "cornerRadiusTopLeft":"17",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8aad6e73611400cb805b0a20ff3b3f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "location":{
                  "x":586,
                  "y":420},
                "size":{
                  "width":349,
                  "height":205},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "cornerRadiusTopLeft":"17",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"677df283314741d69a19a9f9f1992168",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Link in Current Window",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/new_user_login/u4.png"}},
{
          "id":"0999fe6cc1784032854ba86424fe68ad",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":515},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c95e9e0478ab4dda803cc1032e008953",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":550},
            "size":{
              "width":135,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bd15e17df12f4769a148345613613eaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":519},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19bfde7ea2e542c1a54ea47388fa4b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":519},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a84cfd1e609044f3a0c8f7c1cd469d86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":681,
              "y":555},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15c6115fb964c2c98703100d4281ac1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":681,
                  "y":555},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36407f6e16864b24ab6fb05e44c55a56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "opacity":"0.75",
            "location":{
              "x":586,
              "y":175},
            "size":{
              "width":349,
              "height":235},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "cornerRadiusTopLeft":"17",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1aded867484c5dbd451adb745ccca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "opacity":"0.75",
                "location":{
                  "x":586,
                  "y":175},
                "size":{
                  "width":349,
                  "height":235},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "cornerRadiusTopLeft":"17",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u13.png"}},
{
          "id":"f4ce63b92f794041a1c7f4ff10258bd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":721,
              "y":494},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f4cf053ddc5425cb62b0e7ae9b4037b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":721,
                  "y":494},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab015f307b984dfab97f277ad0692a87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":636,
              "y":604},
            "size":{
              "width":94,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d675d5199d54f3d8f9b912ad4b152fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":604},
                "size":{
                  "width":94,
                  "height":14}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"82dcc5874c3a4a27a49b5b54e851c2db",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"11px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Link in Current Window",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"647b5f65aead4c1a942526792e87c227",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":768,
              "y":604},
            "size":{
              "width":91,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e62ae0234eb14f568850e9acdefbc97c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":768,
                  "y":604},
                "size":{
                  "width":91,
                  "height":14}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9dad20aa2a7441c6a418a30f5349206c",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontSize":"11px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Link in Current Window",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba8bbadfae4d4ca9bbc46cee6496b467",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF66CCFF},
            "location":{
              "x":722,
              "y":581},
            "size":{
              "width":78,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"604b3a52e4064762beeae7cede858e6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66CCFF},
                "location":{
                  "x":722,
                  "y":581},
                "size":{
                  "width":78,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open User Hub in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"user_hub.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/new_user_login/u23.png"}},
{
          "id":"f29c25bbe7da48f88797d7003c0d5e1a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":267},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u25_line.png"}},
{
          "id":"4c8a8cfa16c34b778d81607172254a4d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":110,
              "y":261},
            "size":{
              "width":30,
              "height":23},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "outerShadow":{
              "on":false,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4aad1d601434693891af494b96bb915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":110,
                  "y":261},
                "size":{
                  "width":30,
                  "height":23},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u26.png"}},
{
          "id":"b523adc5831f4436b92d5c8ec38ec391",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":267},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u28_line.png"}},
{
          "id":"4f679df641374978932550ac8f463b62",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":294},
            "size":{
              "width":50,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u29_line.png"}},
{
          "id":"7bf0be957bcb48519ecfbb7e3423b442",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":281},
            "size":{
              "width":45,
              "height":10},
            "rotation":"322",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u30_line.png"}},
{
          "id":"419294901b3447f5ab1bdbf200863a22",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1046,
              "y":286},
            "size":{
              "width":175,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u31_line.png"}},
{
          "id":"534a7af41d9448809d90e06dbd93708e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":1016,
              "y":279},
            "size":{
              "width":30,
              "height":23},
            "rotation":"180",
            "textRotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "outerShadow":{
              "on":false,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089fd5d8987e406b8bf1775335059866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":1016,
                  "y":279},
                "size":{
                  "width":30,
                  "height":23},
                "rotation":"180",
                "textRotation":"180",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u26.png"}},
{
          "id":"a1f4b0afcc58437facb840575fc9847a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":286},
            "size":{
              "width":81,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u34_line.png"}},
{
          "id":"d7790f57a7b34840ba60dfa03e48aeb6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1106,
              "y":259},
            "size":{
              "width":50,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u29_line.png"}},
{
          "id":"5fc494f3aed64a26af6fa8986f1fd367",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1067,
              "y":272},
            "size":{
              "width":45,
              "height":10},
            "rotation":"142",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u30_line.png"}},
{
          "id":"e9eb2eb264e2459c8eb28cbdf54a292b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":507},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u37_line.png"}},
{
          "id":"c764a98937e04f08bce1d33b1649f63b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":1045,
              "y":501},
            "size":{
              "width":30,
              "height":23},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "outerShadow":{
              "on":false,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b422eeaab434cfc8967c1e683bb10ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":1045,
                  "y":501},
                "size":{
                  "width":30,
                  "height":23},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u38.png"}},
{
          "id":"11d26458c2a949589cddd8b05d7bac39",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":507},
            "size":{
              "width":195,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u40_line.png"}},
{
          "id":"0ed9f067bdba49c4992d12ad7044b258",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":534},
            "size":{
              "width":50,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u41_line.png"}},
{
          "id":"b03a714da10041c5831dc325bb220281",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":979,
              "y":521},
            "size":{
              "width":45,
              "height":10},
            "rotation":"322",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u42_line.png"}},
{
          "id":"ee0357332a49405c83b1d8948ff60e0f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":518},
            "size":{
              "width":90,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u43_line.png"}},
{
          "id":"f219a84b4049485a88f573a33e831c89",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xF2F2F2},
            "location":{
              "x":81,
              "y":511},
            "size":{
              "width":30,
              "height":23},
            "rotation":"180",
            "textRotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "outerShadow":{
              "on":false,
              "offsetX":2,
              "offsetY":2,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfa851ecd02844f3ad3df835031c73ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xF2F2F2},
                "location":{
                  "x":81,
                  "y":511},
                "size":{
                  "width":30,
                  "height":23},
                "rotation":"180",
                "textRotation":"180",
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "outerShadow":{
                  "on":false,
                  "offsetX":2,
                  "offsetY":2,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u38.png"}},
{
          "id":"f6ef4a1d720c4c898345ecf0faa4b634",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":518},
            "size":{
              "width":81,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u46_line.png"}},
{
          "id":"a3e670c7debc423bb98ab7c5b9c8dd74",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":491},
            "size":{
              "width":31,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u47_line.png"}},
{
          "id":"c83570af3d56426ead7ef848ff3f3f90",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":504},
            "size":{
              "width":45,
              "height":10},
            "rotation":"142",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u42_line.png"}},
{
          "id":"f516a907ba304844908cfadd507795f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":263},
            "size":{
              "width":17,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u49_line.png"}},
{
          "id":"ac8ad995c1284aab9db2b40902f9e861",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":511},
            "size":{
              "width":17,
              "height":10},
            "rotation":"180",
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/new_user_login/u50_line.png"}},
{
          "id":"8c36391270584da7847be17a4a0bcc46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":599,
              "y":188},
            "size":{
              "width":323,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c8f2bea9b4b422e87d4e79d156dad8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":599,
                  "y":188},
                "size":{
                  "width":323,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u51.png"}},
{
          "id":"7fd210e908374b9f8d2b973f0cefae31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF66FFCC},
            "location":{
              "x":640,
              "y":430},
            "size":{
              "width":240,
              "height":35},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4927d48797bd4a32ad8e5aa7136008ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66FFCC},
                "location":{
                  "x":640,
                  "y":430},
                "size":{
                  "width":240,
                  "height":35},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1808049f3aaf4b868871025a72556a56",
                  "label":"",
                  "type":"hyperlink",
                  "styleType":"hyperlink",
                  "visible":true,
                  "style":{
                    "fontName":"'Century Gothic Regular', 'Century Gothic'",
                    "fontSize":"20px"},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Acct Creation in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"acct_creation.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}],
          "images":{
            "normal~":"images/new_user_login/u53.png"}},
{
          "id":"fb7d98d1c2404415a695d6c695fb35be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Century Gothic Regular', 'Century Gothic'",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "paddingTop":"10",
            "location":{
              "x":200,
              "y":175},
            "size":{
              "width":370,
              "height":450},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "cornerRadiusTopLeft":"17",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce1bcaca066b48fdb49ae9b5fb4764e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Century Gothic Regular', 'Century Gothic'",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "paddingTop":"10",
                "location":{
                  "x":200,
                  "y":175},
                "size":{
                  "width":370,
                  "height":450},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "cornerRadiusTopLeft":"17",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_user_login/u56.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7a66c3bd442f48cb9ed746553d032681":{
      "scriptId":"u0"},
    "b00a2eb67a6043ada29cf9939c962ff9":{
      "scriptId":"u1"},
    "6a6b3328667a425aa882e547aeae8e98":{
      "scriptId":"u2"},
    "ed31baaed9d54c32931da332ae5daa09":{
      "scriptId":"u3"},
    "d530fe1c681f41dd92e6142ca62eda22":{
      "scriptId":"u4"},
    "e8aad6e73611400cb805b0a20ff3b3f5":{
      "scriptId":"u5"},
    "677df283314741d69a19a9f9f1992168":{
      "scriptId":"u6"},
    "0999fe6cc1784032854ba86424fe68ad":{
      "scriptId":"u7"},
    "c95e9e0478ab4dda803cc1032e008953":{
      "scriptId":"u8"},
    "bd15e17df12f4769a148345613613eaf":{
      "scriptId":"u9"},
    "19bfde7ea2e542c1a54ea47388fa4b32":{
      "scriptId":"u10"},
    "a84cfd1e609044f3a0c8f7c1cd469d86":{
      "scriptId":"u11"},
    "e15c6115fb964c2c98703100d4281ac1":{
      "scriptId":"u12"},
    "36407f6e16864b24ab6fb05e44c55a56":{
      "scriptId":"u13"},
    "cb1aded867484c5dbd451adb745ccca2":{
      "scriptId":"u14"},
    "f4ce63b92f794041a1c7f4ff10258bd1":{
      "scriptId":"u15"},
    "5f4cf053ddc5425cb62b0e7ae9b4037b":{
      "scriptId":"u16"},
    "ab015f307b984dfab97f277ad0692a87":{
      "scriptId":"u17"},
    "6d675d5199d54f3d8f9b912ad4b152fd":{
      "scriptId":"u18"},
    "82dcc5874c3a4a27a49b5b54e851c2db":{
      "scriptId":"u19"},
    "647b5f65aead4c1a942526792e87c227":{
      "scriptId":"u20"},
    "e62ae0234eb14f568850e9acdefbc97c":{
      "scriptId":"u21"},
    "9dad20aa2a7441c6a418a30f5349206c":{
      "scriptId":"u22"},
    "ba8bbadfae4d4ca9bbc46cee6496b467":{
      "scriptId":"u23"},
    "604b3a52e4064762beeae7cede858e6f":{
      "scriptId":"u24"},
    "f29c25bbe7da48f88797d7003c0d5e1a":{
      "scriptId":"u25"},
    "4c8a8cfa16c34b778d81607172254a4d":{
      "scriptId":"u26"},
    "c4aad1d601434693891af494b96bb915":{
      "scriptId":"u27"},
    "b523adc5831f4436b92d5c8ec38ec391":{
      "scriptId":"u28"},
    "4f679df641374978932550ac8f463b62":{
      "scriptId":"u29"},
    "7bf0be957bcb48519ecfbb7e3423b442":{
      "scriptId":"u30"},
    "419294901b3447f5ab1bdbf200863a22":{
      "scriptId":"u31"},
    "534a7af41d9448809d90e06dbd93708e":{
      "scriptId":"u32"},
    "089fd5d8987e406b8bf1775335059866":{
      "scriptId":"u33"},
    "a1f4b0afcc58437facb840575fc9847a":{
      "scriptId":"u34"},
    "d7790f57a7b34840ba60dfa03e48aeb6":{
      "scriptId":"u35"},
    "5fc494f3aed64a26af6fa8986f1fd367":{
      "scriptId":"u36"},
    "e9eb2eb264e2459c8eb28cbdf54a292b":{
      "scriptId":"u37"},
    "c764a98937e04f08bce1d33b1649f63b":{
      "scriptId":"u38"},
    "4b422eeaab434cfc8967c1e683bb10ef":{
      "scriptId":"u39"},
    "11d26458c2a949589cddd8b05d7bac39":{
      "scriptId":"u40"},
    "0ed9f067bdba49c4992d12ad7044b258":{
      "scriptId":"u41"},
    "b03a714da10041c5831dc325bb220281":{
      "scriptId":"u42"},
    "ee0357332a49405c83b1d8948ff60e0f":{
      "scriptId":"u43"},
    "f219a84b4049485a88f573a33e831c89":{
      "scriptId":"u44"},
    "dfa851ecd02844f3ad3df835031c73ca":{
      "scriptId":"u45"},
    "f6ef4a1d720c4c898345ecf0faa4b634":{
      "scriptId":"u46"},
    "a3e670c7debc423bb98ab7c5b9c8dd74":{
      "scriptId":"u47"},
    "c83570af3d56426ead7ef848ff3f3f90":{
      "scriptId":"u48"},
    "f516a907ba304844908cfadd507795f4":{
      "scriptId":"u49"},
    "ac8ad995c1284aab9db2b40902f9e861":{
      "scriptId":"u50"},
    "8c36391270584da7847be17a4a0bcc46":{
      "scriptId":"u51"},
    "8c8f2bea9b4b422e87d4e79d156dad8c":{
      "scriptId":"u52"},
    "7fd210e908374b9f8d2b973f0cefae31":{
      "scriptId":"u53"},
    "4927d48797bd4a32ad8e5aa7136008ef":{
      "scriptId":"u54"},
    "1808049f3aaf4b868871025a72556a56":{
      "scriptId":"u55"},
    "fb7d98d1c2404415a695d6c695fb35be":{
      "scriptId":"u56"},
    "ce1bcaca066b48fdb49ae9b5fb4764e0":{
      "scriptId":"u57"}}});