$axure.loadCurrentPage({
  "url":"methodology.html",
  "generationDate":new Date(1442793705259.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7f4c55aa687341e4bfa2ec6cc88f035b",
    "type":"Axure:Page",
    "name":"Methodology",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"32c17d73081c4669b020bacc9fce33fa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"ea8a29e264a94912a09c77e7d3604923"}]}},
  "masters":{
    "ea8a29e264a94912a09c77e7d3604923":{
      "packageId":"ea8a29e264a94912a09c77e7d3604923",
      "type":"Axure:Master",
      "name":"Background",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2613c5579c0f43779ce964a53a77715e",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":50},
              "size":{
                "width":1360,
                "height":1070}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":40,
            "fixedVertical":"top",
            "fixedMarginVertical":50,
            "fixedKeepInFront":false,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"d602e3c4aa4d470ca48d3c0898541f51",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"42a0bb87a02943eda6270297978622e6",
                    "label":"",
                    "parentDynamicPanel":"2613c5579c0f43779ce964a53a77715e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"linearGradient",
                        "colors":[{
                            "color":0xFFFFFFFF},
{
                            "color":0xFFFFFFFF},
{
                            "color":0xFF0099FF},
{
                            "color":0xFF0099FF}]},
                      "size":{
                        "width":1440,
                        "height":1120},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"56dd20a44e394e3a8df496b4403887b5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"2613c5579c0f43779ce964a53a77715e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"linearGradient",
                            "colors":[{
                                "color":0xFFFFFFFF},
{
                                "color":0xFFFFFFFF},
{
                                "color":0xFF0099FF},
{
                                "color":0xFF0099FF}]},
                          "size":{
                            "width":1440,
                            "height":1120},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/template/u515.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "32c17d73081c4669b020bacc9fce33fa":{
      "scriptId":"u0",
      "2613c5579c0f43779ce964a53a77715e":{
        "scriptId":"u1"},
      "42a0bb87a02943eda6270297978622e6":{
        "scriptId":"u2"},
      "56dd20a44e394e3a8df496b4403887b5":{
        "scriptId":"u3"}}}});